site_name: Madek Docs
docs_dir: doc
site_dir: _docs_html
markdown_extensions: [tables, fenced_code]
theme: readthedocs

#  tmp: does not work but should:
# markdown_extensions: [tables, fenced_code, wikilinks(base_url='/wiki/', end_url='.html')]


# The Table of contents, files relative to ./doc
# - [ file, main-section, sub-section name/heading ]
pages:
  - ['docs-overview.md']
  - ['manual/manual.md', 'Manual', 'Overview']
  - ['manual/entities/entities.md', 'Manual', 'Entities']
  - ['manual/views.md', 'Manual', 'Views']
  - ['manual/glossary.md', 'Manual', 'Glossary']

  - ['development/development-overview.md', 'Developer', 'Overview']
  - ['development/developer_rules.md', 'Developer', 'Developers Rules']
  - ['development/developer_rules_admin_interface.md',  'Developer', 'Developers Rules (Admin Interface)']
  - ['development/submit_and_review_process.md', 'Developer', 'Code Submit and Review']
  - ['development/git-reflow.md', 'Developer', 'Git Re-Flow']
  - ['development/ui/framework.md', 'Developer', 'UI Framework']
  - ['development/madek_dev_tips.md', 'Developer', 'Dev Tips']
